### ISSUE TITLE
PIN not recognized after initial PIN acceptance

### ISSUE THREAD

**Issue by TheSoundDefense** [IBM-MIL/IBM-Ready-App-for-Insurance#4]
A seller found an issue where he could not connect to Perch after a certain series of steps. Upon opening the app, he entered his simulator PIN, then closed the app before entering the username and password. When he re-opened the app, he was unable to connect using any PIN for several hours.

**Comment by rajohns08** [comment]
I have contacted this seller for more information. Depending on what he tells me, this could be related to #11

**Comment by rajohns08** [comment]
The seller has responded to me saying the error message was "The pin does not exist" which means this issue is the same as #12. Closing this as a duplicate.
