### ISSUE TITLE
Sensor connection hangs after going to email/phone

### ISSUE THREAD

**Issue by TheSoundDefense** [IBM-MIL/IBM-Ready-App-for-Insurance#5]
An IBM seller reported that if he connected to the Perch backend with a PIN, then clicked on an e-mail or phone icon to exit the app, the sensor data would sometimes stop updating upon returning to the app. Need to look into reproducing this.

**Comment by rajohns08** [comment]
Can't work on reproducing this until Bluemix team gets back to me about issue #11. Impossible to actually subscribe to a tag to get push notifications until that gets resolved.

**Comment by rajohns08** [comment]
Just tested this, and it appears to be working fine.
