### ISSUE TITLE
Alert not triggered when AC temperature goes too low

### ISSUE THREAD

**Issue by TheSoundDefense** [IBM-MIL/IBM-Ready-App-for-Insurance#6]
In one instance, the temperature of the Air Conditioner was lowered to -26, but no alert was triggered. This may have been an issue with designing the sensor configuration and should be a quick fix.

**Comment by rajohns08** [comment]
Can't reproduce until Bluemix team gets back to me about issue #11.

**Comment by rajohns08** [comment]
This was functionality was never built into the app. The AC only triggers a notification when hitting 50. There is no "too low" trigger for AC.
