### ISSUE TITLE
Intermittent connection problems while “syncing with sensors”

### ISSUE THREAD

**Issue by trishayy** [IBM-MIL/IBM-Ready-App-for-Insurance#7]
While running the app and logging in using the "demo credentials" the app would get to the "Synching with sensors..." orange screen and never progress beyond that screen.

**Comment by atcabral** [comment]
Does this happen consistently? I haven't run into this on my phone.

**Comment by trishayy** [comment]
It happened to both me and Ricardo for a few hours last week. We had this problem on both physical phones and running from the simulator. Haven't had the problem since, but still should probably be investigated further.

**Comment by rajohns08** [comment]
This can happen if the getAllAssetData query in AssetOverviewDataManager is not successful. There is currently no code to dismiss the syncing with sensors loading screen in this error case. Working on solution.
